Import vec to bridges/primitives/header-chain (#6031)
# Description

I'm unable to build a bridge library due to the errors below, so I am
adding the explicit import to `sp_std::vec`.

## Integration

Projects using it can update their dependency. We are using the branch
`stable2407` (mixed them up in my branch).

## Errors
```
error: cannot find macro `vec` in this scope
  --> /Users/drew/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/88c3250/bridges/primitives/header-chain/src/justification/verification/mod.rs:99:19
   |
99 |         let mut route = vec![];
   |                         ^^^
   |
help: consider importing one of these items
   |
23 + use scale_info::prelude::vec;
   |
23 + use sp_std::vec;
   |

error: cannot find macro `vec` in this scope
   --> /Users/drew/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/88c3250/bridges/primitives/header-chain/src/justification/verification/optimizer.rs:135:36
    |
135 |         duplicate_votes_ancestries_idxs: vec![],
    |                                          ^^^
    |
help: consider importing one of these items
    |
19  + use scale_info::prelude::vec;
    |
19  + use sp_std::vec;
    |

error: cannot find macro `vec` in this scope
   --> /Users/drew/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/88c3250/bridges/primitives/header-chain/src/justification/verification/optimizer.rs:134:21
    |
134 |         extra_precommits: vec![],
    |                           ^^^
    |
help: consider importing one of these items
    |
19  + use scale_info::prelude::vec;
    |
19  + use sp_std::vec;
    |

error: cannot find macro `vec` in this scope
  --> /Users/drew/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/88c3250/bridges/primitives/header-chain/src/justification/verification/equivocation.rs:89:27
   |
89 |         let mut equivocations = vec![];
   |                                 ^^^
   |
help: consider importing one of these items
   |
19 + use scale_info::prelude::vec;
   |
19 + use sp_std::vec;
```

---------

Co-authored-by: Bastian Köcher <git@kchr.de>
Co-authored-by: Serban Iorga <serban@parity.io>
Co-authored-by: command-bot <>
Co-authored-by: Adrian Catangiu <adrian@parity.io>