[pallet-revive] do not silently fail Solidity fixtures compilation (#9474)
This prevents silent failing on compilation errors and using outdated
build artifacts. Instead of ignoring compilation errors and using
outdated fixtures, `cargo test` now bails out early and reports the
problems like this:

```
  Error: failed to compile the Solidity fixtures: [
    {
      "component": "general",
      "errorCode": "2314",
      "formattedMessage": "ParserError: Expected identifier but got '}'\n  --> Flipper.sol:11:1:\n   |\n11 | }\n   | ^\n\n",
      "message": "Expected identifier but got '}'",
      "severity": "error",
      "sourceLocation": {
        "end": 157,
        "file": "Flipper.sol",
        "start": 156
      },
      "type": "ParserError"
    }
  ]
```

Signed-off-by: xermicus <cyrill@parity.io>