ci/check-semver: Fix semver failed step (#6535)
The semver-check is failing with the following
[error](https://github.com/paritytech/polkadot-sdk/actions/runs/11908981132/job/33185572284):

```bash
error[E0658]: use of unstable library feature 'error_in_core'
  --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/frame-decode-0.5.0/src/decoding/extrinsic_decoder.rs:56:6
   |
56 | impl core::error::Error for ExtrinsicDecodeError {}
   |      ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information
   = help: add `#![feature(error_in_core)]` to the crate attributes to enable
   = note: this compiler was built on 2024-05-31; consider upgrading it if it is out of date
```

This is related to the toolchain nightly version 1.80. In rust, 1.81 the
`core::error::Error` is stable.

After updating the rust-toolchain, parity-publish crate must be updated
as well.
The `cargo-semver-checks` dependency of `parity-publish` crate is
updated from 0.34 to 0.38.
This update enables rustdoc v36 that fixes the following
[issue](https://github.com/paritytech/polkadot-sdk/actions/runs/11912689841/job/33196936011):


```bash
 validating prdocs...
checking file changes...
checking semver changes...
(1/18) building frame-support-HEAD...
(2/18) building frame-support-28.0.0...
Error: rustdoc format v36 for file /__w/polkadot-sdk/polkadot-sdk/target/doc/frame_support.new is not supported
```

This PR is pending on a release of parity-publish to version 0.9.0
(fixes already on origin/master)

---------

Signed-off-by: Alexandru Vasile <alexandru.vasile@parity.io>