[Release|CI/CD] Put exact version of solidity on MacOS runner that is compatible with solc (#10668)
The MacOS binary build is failing with:
`Error: resolc compilation failed: `solc` versions >0.8.30 are not
supported, found 0.8.31`

Since the same is not happening on master or on `stable2512` - currently
pushing fix just to this branch.