Fix eth-rpc publish (#10580)
Generatate the subxt metadata in OUT_DIR
not doing so generate the following error when we try to publish the
package


```
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 403 Forbidden): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.

```

see related subxt changes: https://github.com/paritytech/subxt/pull/2142

---------

Co-authored-by: cmd[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: xermicus <cyrill@parity.io>